'use client';
import {
  Home, Leaf, Package, CloudSun, DollarSign, CheckSquare,
  Users, Shield, BarChart3, Settings, Bell, Search, Plus,
  ChevronRight, ChevronLeft, ChevronDown, ChevronUp,
  ArrowUp, ArrowDown, TrendingUp, TrendingDown,
  AlertTriangle, AlertCircle, CheckCircle2, XCircle,
  Wifi, WifiOff, RefreshCw, Upload, Download,
  Camera, MapPin, Clock, Calendar, Filter,
  Edit2, Trash2, MoreVertical, Eye, EyeOff,
  Droplets, Thermometer, Wind, Sun, CloudRain,
  Tractor, Sprout, Wheat, Apple, Fish,
  Scale, Beaker, Syringe, Heart,
  CreditCard, Receipt, PiggyBank, TrendingUp as Finance,
  BookOpen, FileText, FilePlus, FileCheck,
  Lock, Unlock, UserCheck, UserX, Key,
  Star, Zap, Activity, BarChart2, PieChart,
  Globe, Building2, Factory, Warehouse,
  ArrowRightLeft, ArrowRight, Layers, Grid3X3, List,
  X, Check, Minus, ChevronRight as Arrow,
  UserCircle, LogOut, HelpCircle, Info,
  Clipboard, ClipboardCheck, ClipboardList,
  ShieldCheck, ShieldAlert, ShieldOff,
  SlidersHorizontal, ToggleLeft, ToggleRight,
  Maximize2, Minimize2, ExternalLink,
  Moon,
  // New icons for AI chat, onboarding, customise
  MessageSquare, MessageCircle,
  Send, Bot,
  UserRound as UserSingle,
  Phone, Mail, Palette,
  Sparkles,
  Archive, RotateCcw,
} from 'lucide-react';

export {
  Home, Leaf, Package, CloudSun, DollarSign, CheckSquare,
  Users, Shield, BarChart3, Settings, Bell, Search, Plus,
  ChevronRight, ChevronLeft, ChevronDown, ChevronUp,
  ArrowUp, ArrowDown, TrendingUp, TrendingDown,
  AlertTriangle, AlertCircle, CheckCircle2, XCircle,
  Wifi, WifiOff, RefreshCw, Upload, Download,
  Camera, MapPin, Clock, Calendar, Filter,
  Edit2, Trash2, MoreVertical, Eye, EyeOff,
  Droplets, Thermometer, Wind, Sun, CloudRain,
  Tractor, Sprout, Wheat, Apple, Fish,
  Scale, Beaker, Syringe, Heart,
  CreditCard, Receipt, PiggyBank, Finance,
  BookOpen, FileText, FilePlus, FileCheck,
  Lock, Unlock, UserCheck, UserX, Key,
  Star, Zap, Activity, BarChart2, PieChart,
  Globe, Building2, Factory, Warehouse,
  ArrowRightLeft, ArrowRight, Layers, Grid3X3, List,
  X, Check, Minus, Arrow,
  UserCircle, LogOut, HelpCircle, Info,
  Clipboard, ClipboardCheck, ClipboardList,
  ShieldCheck, ShieldAlert, ShieldOff,
  SlidersHorizontal, ToggleLeft, ToggleRight,
  Maximize2, Minimize2, ExternalLink,
  Moon,
  MessageSquare, MessageCircle,
  Send, Bot,
  UserSingle,
  Phone, Mail, Palette,
  Sparkles,
  Archive, RotateCcw,
};
